#---Profile Properties---
#Available profiles: local, remote, docker
#Set remote when deploy to server
spring:
  profiles:
    active: local
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp


#  data:
#    mongodb:
#      database: erp
#      uri: mongodb://127.0.0.1:27017
##---Loggin Properties---
logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.web.servlet.mvc.method.annotation: debug
    org.springframework.boot.actuate.endpoint.mvc: debug
    com.csipon.erp: debug
server:
  port: 8888